import ExcelJS from 'exceljs';

import { EXPORT_SHEET_NAME_MAX } from '../../types/export';
import type { ExportResult } from './run-export';

/**
 * Write an export result to a real .xlsx workbook.
 *
 * Two sheets, always. The first is the data. The second — "Export notes" —
 * records what the file contains and, more importantly, what it does not: the
 * filters applied, whether the row cap truncated the result, how a fuzzy
 * reference-table join actually performed. A spreadsheet gets forwarded,
 * archived and quoted back months later with none of the context it was
 * generated under, and a number nobody can qualify is worse than no number.
 */

const NOTES_SHEET_NAME = 'Export notes';

/** Excel's own limits, enforced here so the file never opens as "corrupt". */
const sanitizeSheetName = (name: string) =>
  name.replace(/[:\\/?*[\]]/g, ' ').trim().slice(0, EXPORT_SHEET_NAME_MAX) || 'Export';

/** Roughly fit the column to its content without pinning it to an outlier. */
const columnWidth = (header: string, samples: (string | number | boolean | Date | null)[]) => {
  const widest = samples.reduce<number>((max, value) => {
    if (value === null) return max;
    const length = value instanceof Date ? 19 : String(value).length;
    return Math.max(max, length);
  }, header.length);

  return Math.min(60, Math.max(10, widest + 2));
};

export const buildWorkbook = async ({
  result,
  sheetName,
  generatedBy,
  generatedAt,
  filterSummary,
}: {
  result: ExportResult;
  sheetName?: string;
  generatedBy: string;
  generatedAt: Date;
  filterSummary: string[];
}): Promise<Buffer> => {
  const workbook = new ExcelJS.Workbook();
  workbook.created = generatedAt;
  workbook.creator = 'HubSign';

  const sheet = workbook.addWorksheet(sanitizeSheetName(sheetName || result.datasetLabel));

  sheet.columns = result.columns.map((column, index) => ({
    header: column.label,
    key: `c${index}`,
    width: columnWidth(
      column.label,
      // Sampling the first 200 rows keeps sizing cheap on a large export while
      // still reflecting real content rather than just the header.
      result.rows.slice(0, 200).map((row) => row[index]),
    ),
  }));

  const header = sheet.getRow(1);
  header.font = { bold: true };
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F0FB' } };
  header.alignment = { vertical: 'middle' };
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  for (const row of result.rows) {
    sheet.addRow(Object.fromEntries(row.map((value, index) => [`c${index}`, value])));
  }

  // Number and date formats, applied per column so the sheet can be summed,
  // sorted and pivoted rather than merely read.
  result.columns.forEach((column, index) => {
    const target = sheet.getColumn(`c${index}`);

    switch (column.type) {
      case 'money':
        target.numFmt = '#,##0.00';
        target.alignment = { horizontal: 'right' };
        break;
      case 'number':
        target.alignment = { horizontal: 'right' };
        break;
      case 'date':
        target.numFmt = 'yyyy-mm-dd';
        break;
      case 'datetime':
        target.numFmt = 'yyyy-mm-dd hh:mm';
        break;
      default:
        break;
    }
  });

  // An auto-filter across the header turns the sheet into something someone can
  // actually work in, which is the entire point of exporting to Excel.
  if (result.columns.length > 0 && result.rows.length > 0) {
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: result.columns.length },
    };
  }

  const notes = workbook.addWorksheet(NOTES_SHEET_NAME);
  notes.columns = [
    { header: '', key: 'label', width: 26 },
    { header: '', key: 'value', width: 110 },
  ];

  const line = (label: string, value: string) => notes.addRow({ label, value });

  line('Export', result.datasetLabel);
  line('Generated', generatedAt.toISOString());
  line('Generated by', generatedBy);
  line('Rows in this file', String(result.rowCount));
  line('Rows matching filters', String(result.totalMatching));
  line('Columns', String(result.columns.length));

  notes.addRow({});
  line('Filters', filterSummary.length > 0 ? '' : 'None — every row in the dataset.');
  for (const filter of filterSummary) {
    notes.addRow({ label: '', value: filter });
  }

  if (result.notes.length > 0) {
    notes.addRow({});
    line('Please note', '');
    for (const note of result.notes) {
      notes.addRow({ label: '', value: note });
    }
  }

  notes.getColumn('label').font = { bold: true };
  notes.getColumn('value').alignment = { wrapText: true, vertical: 'top' };

  // exceljs types this as ExcelJS.Buffer (an ArrayBuffer-alike); Node's Buffer
  // is what the HTTP layer wants.
  const written = await workbook.xlsx.writeBuffer();

  return Buffer.from(written);
};
